/* Auto-generated from chromium/src/net/base/net_error_list.h; do not edit. */

export const list = {
  '-1': 'IO_PENDING',
  '-2': 'FAILED',
  '-3': 'ABORTED',
  '-4': 'INVALID_ARGUMENT',
  '-5': 'INVALID_HANDLE',
  '-6': 'FILE_NOT_FOUND',
  '-7': 'TIMED_OUT',
  '-8': 'FILE_TOO_BIG',
  '-9': 'UNEXPECTED',
  '-10': 'ACCESS_DENIED',
  '-11': 'NOT_IMPLEMENTED',
  '-12': 'INSUFFICIENT_RESOURCES',
  '-13': 'OUT_OF_MEMORY',
  '-14': 'UPLOAD_FILE_CHANGED',
  '-15': 'SOCKET_NOT_CONNECTED',
  '-16': 'FILE_EXISTS',
  '-17': 'FILE_PATH_TOO_LONG',
  '-18': 'FILE_NO_SPACE',
  '-19': 'FILE_VIRUS_INFECTED',
  '-20': 'BLOCKED_BY_CLIENT',
  '-21': 'NETWORK_CHANGED',
  '-22': 'BLOCKED_BY_ADMINISTRATOR',
  '-23': 'SOCKET_IS_CONNECTED',
  '-100': 'CONNECTION_CLOSED',
  '-101': 'CONNECTION_RESET',
  '-102': 'CONNECTION_REFUSED',
  '-103': 'CONNECTION_ABORTED',
  '-104': 'CONNECTION_FAILED',
  '-105': 'NAME_NOT_RESOLVED',
  '-106': 'INTERNET_DISCONNECTED',
  '-107': 'SSL_PROTOCOL_ERROR',
  '-108': 'ADDRESS_INVALID',
  '-109': 'ADDRESS_UNREACHABLE',
  '-110': 'SSL_CLIENT_AUTH_CERT_NEEDED',
  '-111': 'TUNNEL_CONNECTION_FAILED',
  '-112': 'NO_SSL_VERSIONS_ENABLED',
  '-113': 'SSL_VERSION_OR_CIPHER_MISMATCH',
  '-114': 'SSL_RENEGOTIATION_REQUESTED',
  '-115': 'PROXY_AUTH_UNSUPPORTED',
  '-116': 'CERT_ERROR_IN_SSL_RENEGOTIATION',
  '-117': 'BAD_SSL_CLIENT_AUTH_CERT',
  '-118': 'CONNECTION_TIMED_OUT',
  '-119': 'HOST_RESOLVER_QUEUE_TOO_LARGE',
  '-120': 'SOCKS_CONNECTION_FAILED',
  '-121': 'SOCKS_CONNECTION_HOST_UNREACHABLE',
  '-122': 'NPN_NEGOTIATION_FAILED',
  '-123': 'SSL_NO_RENEGOTIATION',
  '-124': 'WINSOCK_UNEXPECTED_WRITTEN_BYTES',
  '-125': 'SSL_DECOMPRESSION_FAILURE_ALERT',
  '-126': 'SSL_BAD_RECORD_MAC_ALERT',
  '-127': 'PROXY_AUTH_REQUESTED',
  '-128': 'SSL_UNSAFE_NEGOTIATION',
  '-129': 'SSL_WEAK_SERVER_EPHEMERAL_DH_KEY',
  '-130': 'PROXY_CONNECTION_FAILED',
  '-131': 'MANDATORY_PROXY_CONFIGURATION_FAILED',
  '-133': 'PRECONNECT_MAX_SOCKET_LIMIT',
  '-134': 'SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED',
  '-135': 'SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY',
  '-136': 'PROXY_CERTIFICATE_INVALID',
  '-137': 'NAME_RESOLUTION_FAILED',
  '-138': 'NETWORK_ACCESS_DENIED',
  '-139': 'TEMPORARILY_THROTTLED',
  '-140': 'HTTPS_PROXY_TUNNEL_RESPONSE',
  '-141': 'SSL_CLIENT_AUTH_SIGNATURE_FAILED',
  '-142': 'MSG_TOO_BIG',
  '-143': 'SPDY_SESSION_ALREADY_EXISTS',
  '-145': 'WS_PROTOCOL_ERROR',
  '-146': 'PROTOCOL_SWITCHED',
  '-147': 'ADDRESS_IN_USE',
  '-148': 'SSL_HANDSHAKE_NOT_COMPLETED',
  '-149': 'SSL_BAD_PEER_PUBLIC_KEY',
  '-150': 'SSL_PINNED_KEY_NOT_IN_CERT_CHAIN',
  '-151': 'CLIENT_AUTH_CERT_TYPE_UNSUPPORTED',
  '-152': 'ORIGIN_BOUND_CERT_GENERATION_TYPE_MISMATCH',
  '-153': 'SSL_DECRYPT_ERROR_ALERT',
  '-154': 'WS_THROTTLE_QUEUE_TOO_LARGE',
  '-155': 'TOO_MANY_SOCKET_STREAMS',
  '-156': 'SSL_SERVER_CERT_CHANGED',
  '-157': 'SSL_INAPPROPRIATE_FALLBACK',
  '-158': 'CT_NO_SCTS_VERIFIED_OK',
  '-200': 'CERT_COMMON_NAME_INVALID',
  '-201': 'CERT_DATE_INVALID',
  '-202': 'CERT_AUTHORITY_INVALID',
  '-203': 'CERT_CONTAINS_ERRORS',
  '-204': 'CERT_NO_REVOCATION_MECHANISM',
  '-205': 'CERT_UNABLE_TO_CHECK_REVOCATION',
  '-206': 'CERT_REVOKED',
  '-207': 'CERT_INVALID',
  '-208': 'CERT_WEAK_SIGNATURE_ALGORITHM',
  '-210': 'CERT_NON_UNIQUE_NAME',
  '-211': 'CERT_WEAK_KEY',
  '-212': 'CERT_NAME_CONSTRAINT_VIOLATION',
  '-213': 'CERT_END',
  '-300': 'INVALID_URL',
  '-301': 'DISALLOWED_URL_SCHEME',
  '-302': 'UNKNOWN_URL_SCHEME',
  '-310': 'TOO_MANY_REDIRECTS',
  '-311': 'UNSAFE_REDIRECT',
  '-312': 'UNSAFE_PORT',
  '-320': 'INVALID_RESPONSE',
  '-321': 'INVALID_CHUNKED_ENCODING',
  '-322': 'METHOD_NOT_SUPPORTED',
  '-323': 'UNEXPECTED_PROXY_AUTH',
  '-324': 'EMPTY_RESPONSE',
  '-325': 'RESPONSE_HEADERS_TOO_BIG',
  '-326': 'PAC_STATUS_NOT_OK',
  '-327': 'PAC_SCRIPT_FAILED',
  '-328': 'REQUEST_RANGE_NOT_SATISFIABLE',
  '-329': 'MALFORMED_IDENTITY',
  '-330': 'CONTENT_DECODING_FAILED',
  '-331': 'NETWORK_IO_SUSPENDED',
  '-332': 'SYN_REPLY_NOT_RECEIVED',
  '-333': 'ENCODING_CONVERSION_FAILED',
  '-334': 'UNRECOGNIZED_FTP_DIRECTORY_LISTING_FORMAT',
  '-335': 'INVALID_SPDY_STREAM',
  '-336': 'NO_SUPPORTED_PROXIES',
  '-337': 'SPDY_PROTOCOL_ERROR',
  '-338': 'INVALID_AUTH_CREDENTIALS',
  '-339': 'UNSUPPORTED_AUTH_SCHEME',
  '-340': 'ENCODING_DETECTION_FAILED',
  '-341': 'MISSING_AUTH_CREDENTIALS',
  '-342': 'UNEXPECTED_SECURITY_LIBRARY_STATUS',
  '-343': 'MISCONFIGURED_AUTH_ENVIRONMENT',
  '-344': 'UNDOCUMENTED_SECURITY_LIBRARY_STATUS',
  '-345': 'RESPONSE_BODY_TOO_BIG_TO_DRAIN',
  '-346': 'RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH',
  '-347': 'INCOMPLETE_SPDY_HEADERS',
  '-348': 'PAC_NOT_IN_DHCP',
  '-349': 'RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION',
  '-350': 'RESPONSE_HEADERS_MULTIPLE_LOCATION',
  '-351': 'SPDY_SERVER_REFUSED_STREAM',
  '-352': 'SPDY_PING_FAILED',
  '-353': 'PIPELINE_EVICTION',
  '-354': 'CONTENT_LENGTH_MISMATCH',
  '-355': 'INCOMPLETE_CHUNKED_ENCODING',
  '-356': 'QUIC_PROTOCOL_ERROR',
  '-357': 'RESPONSE_HEADERS_TRUNCATED',
  '-358': 'QUIC_HANDSHAKE_FAILED',
  '-400': 'CACHE_MISS',
  '-401': 'CACHE_READ_FAILURE',
  '-402': 'CACHE_WRITE_FAILURE',
  '-403': 'CACHE_OPERATION_NOT_SUPPORTED',
  '-404': 'CACHE_OPEN_FAILURE',
  '-405': 'CACHE_CREATE_FAILURE',
  '-406': 'CACHE_RACE',
  '-407': 'CACHE_CHECKSUM_READ_FAILURE',
  '-408': 'CACHE_CHECKSUM_MISMATCH',
  '-501': 'INSECURE_RESPONSE',
  '-502': 'NO_PRIVATE_KEY_FOR_CERT',
  '-503': 'ADD_USER_CERT_FAILED',
  '-601': 'FTP_FAILED',
  '-602': 'FTP_SERVICE_UNAVAILABLE',
  '-603': 'FTP_TRANSFER_ABORTED',
  '-604': 'FTP_FILE_BUSY',
  '-605': 'FTP_SYNTAX_ERROR',
  '-606': 'FTP_COMMAND_NOT_SUPPORTED',
  '-607': 'FTP_BAD_COMMAND_SEQUENCE',
  '-701': 'PKCS12_IMPORT_BAD_PASSWORD',
  '-702': 'PKCS12_IMPORT_FAILED',
  '-703': 'IMPORT_CA_CERT_NOT_CA',
  '-704': 'IMPORT_CERT_ALREADY_EXISTS',
  '-705': 'IMPORT_CA_CERT_FAILED',
  '-706': 'IMPORT_SERVER_CERT_FAILED',
  '-707': 'PKCS12_IMPORT_INVALID_MAC',
  '-708': 'PKCS12_IMPORT_INVALID_FILE',
  '-709': 'PKCS12_IMPORT_UNSUPPORTED',
  '-710': 'KEY_GENERATION_FAILED',
  '-711': 'ORIGIN_BOUND_CERT_GENERATION_FAILED',
  '-712': 'PRIVATE_KEY_EXPORT_FAILED',
  '-713': 'SELF_SIGNED_CERT_GENERATION_FAILED',
  '-714': 'CERT_DATABASE_CHANGED',
  '-800': 'DNS_MALFORMED_RESPONSE',
  '-801': 'DNS_SERVER_REQUIRES_TCP',
  '-802': 'DNS_SERVER_FAILED',
  '-803': 'DNS_TIMED_OUT',
  '-804': 'DNS_CACHE_MISS',
  '-805': 'DNS_SEARCH_EMPTY',
  '-806': 'DNS_SORT_ERROR',
};

export const IO_PENDING = -1;
export const FAILED = -2;
export const ABORTED = -3;
export const INVALID_ARGUMENT = -4;
export const INVALID_HANDLE = -5;
export const FILE_NOT_FOUND = -6;
export const TIMED_OUT = -7;
export const FILE_TOO_BIG = -8;
export const UNEXPECTED = -9;
export const ACCESS_DENIED = -10;
export const NOT_IMPLEMENTED = -11;
export const INSUFFICIENT_RESOURCES = -12;
export const OUT_OF_MEMORY = -13;
export const UPLOAD_FILE_CHANGED = -14;
export const SOCKET_NOT_CONNECTED = -15;
export const FILE_EXISTS = -16;
export const FILE_PATH_TOO_LONG = -17;
export const FILE_NO_SPACE = -18;
export const FILE_VIRUS_INFECTED = -19;
export const BLOCKED_BY_CLIENT = -20;
export const NETWORK_CHANGED = -21;
export const BLOCKED_BY_ADMINISTRATOR = -22;
export const SOCKET_IS_CONNECTED = -23;
export const CONNECTION_CLOSED = -100;
export const CONNECTION_RESET = -101;
export const CONNECTION_REFUSED = -102;
export const CONNECTION_ABORTED = -103;
export const CONNECTION_FAILED = -104;
export const NAME_NOT_RESOLVED = -105;
export const INTERNET_DISCONNECTED = -106;
export const SSL_PROTOCOL_ERROR = -107;
export const ADDRESS_INVALID = -108;
export const ADDRESS_UNREACHABLE = -109;
export const SSL_CLIENT_AUTH_CERT_NEEDED = -110;
export const TUNNEL_CONNECTION_FAILED = -111;
export const NO_SSL_VERSIONS_ENABLED = -112;
export const SSL_VERSION_OR_CIPHER_MISMATCH = -113;
export const SSL_RENEGOTIATION_REQUESTED = -114;
export const PROXY_AUTH_UNSUPPORTED = -115;
export const CERT_ERROR_IN_SSL_RENEGOTIATION = -116;
export const BAD_SSL_CLIENT_AUTH_CERT = -117;
export const CONNECTION_TIMED_OUT = -118;
export const HOST_RESOLVER_QUEUE_TOO_LARGE = -119;
export const SOCKS_CONNECTION_FAILED = -120;
export const SOCKS_CONNECTION_HOST_UNREACHABLE = -121;
export const NPN_NEGOTIATION_FAILED = -122;
export const SSL_NO_RENEGOTIATION = -123;
export const WINSOCK_UNEXPECTED_WRITTEN_BYTES = -124;
export const SSL_DECOMPRESSION_FAILURE_ALERT = -125;
export const SSL_BAD_RECORD_MAC_ALERT = -126;
export const PROXY_AUTH_REQUESTED = -127;
export const SSL_UNSAFE_NEGOTIATION = -128;
export const SSL_WEAK_SERVER_EPHEMERAL_DH_KEY = -129;
export const PROXY_CONNECTION_FAILED = -130;
export const MANDATORY_PROXY_CONFIGURATION_FAILED = -131;
export const PRECONNECT_MAX_SOCKET_LIMIT = -133;
export const SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED = -134;
export const SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY = -135;
export const PROXY_CERTIFICATE_INVALID = -136;
export const NAME_RESOLUTION_FAILED = -137;
export const NETWORK_ACCESS_DENIED = -138;
export const TEMPORARILY_THROTTLED = -139;
export const HTTPS_PROXY_TUNNEL_RESPONSE = -140;
export const SSL_CLIENT_AUTH_SIGNATURE_FAILED = -141;
export const MSG_TOO_BIG = -142;
export const SPDY_SESSION_ALREADY_EXISTS = -143;
export const WS_PROTOCOL_ERROR = -145;
export const PROTOCOL_SWITCHED = -146;
export const ADDRESS_IN_USE = -147;
export const SSL_HANDSHAKE_NOT_COMPLETED = -148;
export const SSL_BAD_PEER_PUBLIC_KEY = -149;
export const SSL_PINNED_KEY_NOT_IN_CERT_CHAIN = -150;
export const CLIENT_AUTH_CERT_TYPE_UNSUPPORTED = -151;
export const ORIGIN_BOUND_CERT_GENERATION_TYPE_MISMATCH = -152;
export const SSL_DECRYPT_ERROR_ALERT = -153;
export const WS_THROTTLE_QUEUE_TOO_LARGE = -154;
export const TOO_MANY_SOCKET_STREAMS = -155;
export const SSL_SERVER_CERT_CHANGED = -156;
export const SSL_INAPPROPRIATE_FALLBACK = -157;
export const CT_NO_SCTS_VERIFIED_OK = -158;
export const CERT_COMMON_NAME_INVALID = -200;
export const CERT_DATE_INVALID = -201;
export const CERT_AUTHORITY_INVALID = -202;
export const CERT_CONTAINS_ERRORS = -203;
export const CERT_NO_REVOCATION_MECHANISM = -204;
export const CERT_UNABLE_TO_CHECK_REVOCATION = -205;
export const CERT_REVOKED = -206;
export const CERT_INVALID = -207;
export const CERT_WEAK_SIGNATURE_ALGORITHM = -208;
export const CERT_NON_UNIQUE_NAME = -210;
export const CERT_WEAK_KEY = -211;
export const CERT_NAME_CONSTRAINT_VIOLATION = -212;
export const CERT_END = -213;
export const INVALID_URL = -300;
export const DISALLOWED_URL_SCHEME = -301;
export const UNKNOWN_URL_SCHEME = -302;
export const TOO_MANY_REDIRECTS = -310;
export const UNSAFE_REDIRECT = -311;
export const UNSAFE_PORT = -312;
export const INVALID_RESPONSE = -320;
export const INVALID_CHUNKED_ENCODING = -321;
export const METHOD_NOT_SUPPORTED = -322;
export const UNEXPECTED_PROXY_AUTH = -323;
export const EMPTY_RESPONSE = -324;
export const RESPONSE_HEADERS_TOO_BIG = -325;
export const PAC_STATUS_NOT_OK = -326;
export const PAC_SCRIPT_FAILED = -327;
export const REQUEST_RANGE_NOT_SATISFIABLE = -328;
export const MALFORMED_IDENTITY = -329;
export const CONTENT_DECODING_FAILED = -330;
export const NETWORK_IO_SUSPENDED = -331;
export const SYN_REPLY_NOT_RECEIVED = -332;
export const ENCODING_CONVERSION_FAILED = -333;
export const UNRECOGNIZED_FTP_DIRECTORY_LISTING_FORMAT = -334;
export const INVALID_SPDY_STREAM = -335;
export const NO_SUPPORTED_PROXIES = -336;
export const SPDY_PROTOCOL_ERROR = -337;
export const INVALID_AUTH_CREDENTIALS = -338;
export const UNSUPPORTED_AUTH_SCHEME = -339;
export const ENCODING_DETECTION_FAILED = -340;
export const MISSING_AUTH_CREDENTIALS = -341;
export const UNEXPECTED_SECURITY_LIBRARY_STATUS = -342;
export const MISCONFIGURED_AUTH_ENVIRONMENT = -343;
export const UNDOCUMENTED_SECURITY_LIBRARY_STATUS = -344;
export const RESPONSE_BODY_TOO_BIG_TO_DRAIN = -345;
export const RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH = -346;
export const INCOMPLETE_SPDY_HEADERS = -347;
export const PAC_NOT_IN_DHCP = -348;
export const RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION = -349;
export const RESPONSE_HEADERS_MULTIPLE_LOCATION = -350;
export const SPDY_SERVER_REFUSED_STREAM = -351;
export const SPDY_PING_FAILED = -352;
export const PIPELINE_EVICTION = -353;
export const CONTENT_LENGTH_MISMATCH = -354;
export const INCOMPLETE_CHUNKED_ENCODING = -355;
export const QUIC_PROTOCOL_ERROR = -356;
export const RESPONSE_HEADERS_TRUNCATED = -357;
export const QUIC_HANDSHAKE_FAILED = -358;
export const CACHE_MISS = -400;
export const CACHE_READ_FAILURE = -401;
export const CACHE_WRITE_FAILURE = -402;
export const CACHE_OPERATION_NOT_SUPPORTED = -403;
export const CACHE_OPEN_FAILURE = -404;
export const CACHE_CREATE_FAILURE = -405;
export const CACHE_RACE = -406;
export const CACHE_CHECKSUM_READ_FAILURE = -407;
export const CACHE_CHECKSUM_MISMATCH = -408;
export const INSECURE_RESPONSE = -501;
export const NO_PRIVATE_KEY_FOR_CERT = -502;
export const ADD_USER_CERT_FAILED = -503;
export const FTP_FAILED = -601;
export const FTP_SERVICE_UNAVAILABLE = -602;
export const FTP_TRANSFER_ABORTED = -603;
export const FTP_FILE_BUSY = -604;
export const FTP_SYNTAX_ERROR = -605;
export const FTP_COMMAND_NOT_SUPPORTED = -606;
export const FTP_BAD_COMMAND_SEQUENCE = -607;
export const PKCS12_IMPORT_BAD_PASSWORD = -701;
export const PKCS12_IMPORT_FAILED = -702;
export const IMPORT_CA_CERT_NOT_CA = -703;
export const IMPORT_CERT_ALREADY_EXISTS = -704;
export const IMPORT_CA_CERT_FAILED = -705;
export const IMPORT_SERVER_CERT_FAILED = -706;
export const PKCS12_IMPORT_INVALID_MAC = -707;
export const PKCS12_IMPORT_INVALID_FILE = -708;
export const PKCS12_IMPORT_UNSUPPORTED = -709;
export const KEY_GENERATION_FAILED = -710;
export const ORIGIN_BOUND_CERT_GENERATION_FAILED = -711;
export const PRIVATE_KEY_EXPORT_FAILED = -712;
export const SELF_SIGNED_CERT_GENERATION_FAILED = -713;
export const CERT_DATABASE_CHANGED = -714;
export const DNS_MALFORMED_RESPONSE = -800;
export const DNS_SERVER_REQUIRES_TCP = -801;
export const DNS_SERVER_FAILED = -802;
export const DNS_TIMED_OUT = -803;
export const DNS_CACHE_MISS = -804;
export const DNS_SEARCH_EMPTY = -805;
export const DNS_SORT_ERROR = -806;
